/* SPDX-License-Identifier: Apache-2.0 AND MIT */
#include "slhdsa_wrapper.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

extern void sha2_256(uint8_t *md, const void *m, size_t m_sz);

static const char *param_names[] = {
    "SLH-DSA-SHA2-128s",  "SLH-DSA-SHA2-128f",  "SLH-DSA-SHA2-192s",
    "SLH-DSA-SHA2-192f",  "SLH-DSA-SHA2-256s",  "SLH-DSA-SHA2-256f",
    "SLH-DSA-SHAKE-128s", "SLH-DSA-SHAKE-128f", "SLH-DSA-SHAKE-192s",
    "SLH-DSA-SHAKE-192f", "SLH-DSA-SHAKE-256s", "SLH-DSA-SHAKE-256f",
};

static const char *c_names[] = {
    "sha2_128s",  "sha2_128f",  "sha2_192s",  "sha2_192f",
    "sha2_256s",  "sha2_256f",  "shake_128s", "shake_128f",
    "shake_192s", "shake_192f", "shake_256s", "shake_256f",
};

static const size_t n_vals[] = {
    16, 16, 24, 24, 32, 32, 16, 16, 24, 24, 32, 32,
};

static const uint8_t test_msg[]
    = {0x54, 0x65, 0x73, 0x74, 0x20, 0x6d, 0x65, 0x73, 0x73, 0x61,
       0x67, 0x65, 0x20, 0x66, 0x6f, 0x72, 0x20, 0x4b, 0x41, 0x54};

static void print_array(const char *name, const uint8_t *data, size_t len)
{
    size_t i;
    printf("static const unsigned char %s[] = {\n    ", name);
    for (i = 0; i < len; i++) {
        printf("0x%02x", data[i]);
        if (i < len - 1) {
            printf(", ");
            if ((i + 1) % 12 == 0)
                printf("\n    ");
        }
    }
    printf("\n};\n\n");
}

int main(void)
{
    int i;

    fprintf(stderr,
            "NOTE: this is a diagnostic tool. POST KAT values are maintained "
            "in qudo-pqc/src/qudo_self_test_data.inc. Do not use this tool "
            "to overwrite the canonical .inc file without FIPS 140-3 §7.10 "
            "review. NIST-traced ACVP vectors live under qudo-pqc/acvp/.\n");

    printf(
        "/*\n"
        " * Generated by qudo-pqc/tools/gen_slhdsa_kat — DIAGNOSTIC ONLY.\n"
        " *\n"
        " * Canonical POST KAT values: qudo-pqc/src/qudo_self_test_data.inc\n"
        " * NIST-traced ACVP vectors:  qudo-pqc/acvp/ (see acvp/README.md)\n"
        " *\n"
        " * FIPS 140-3 (ISO/IEC 19790) §7.10 review required before any\n"
        " * change to the canonical .inc.\n"
        " */\n\n");

    QUDO_SLHDSA_init();

    for (i = 0; i < 12; i++) {
        const char *pname = param_names[i];
        const char *cname = c_names[i];
        size_t n = n_vals[i];

        fprintf(stderr, "Generating KAT for %s (n=%zu)...\n", pname, n);

        QUDO_SLHDSA *sig = QUDO_SLHDSA_new(pname);
        if (!sig) {
            fprintf(stderr, "ERROR: QUDO_SLHDSA_new(%s) failed\n", pname);
            return 1;
        }

        size_t pk_len = sig->length_public_key;
        size_t sk_len = sig->length_secret_key;
        size_t max_sig_len = sig->length_signature;

        uint8_t *pk = calloc(1, pk_len);
        uint8_t *sk = calloc(1, sk_len);
        uint8_t *sig_buf = calloc(1, max_sig_len);
        if (!pk || !sk || !sig_buf) {
            fprintf(stderr, "ERROR: malloc failed\n");
            return 1;
        }

        uint8_t sk_seed[32], sk_prf[32], pk_seed[32];
        size_t j;
        memset(sk_seed, 0, sizeof(sk_seed));
        memset(sk_prf, 0, sizeof(sk_prf));
        memset(pk_seed, 0, sizeof(pk_seed));

        for (j = 0; j < n; j++) {
            sk_seed[j] = (uint8_t)(0x60 + i * 0x10 + j);
            sk_prf[j] = (uint8_t)(0x60 + i * 0x10 + n + j);
            pk_seed[j] = (uint8_t)(0x60 + i * 0x10 + 2 * n + j);
        }

        QUDO_SLHDSA_status_t rc = QUDO_SLHDSA_keypair_internal(
            sig, pk, sk, sk_seed, sk_prf, pk_seed);
        if (rc != QUDO_SLHDSA_SUCCESS) {
            fprintf(stderr, "ERROR: keypair_internal(%s) = %d\n", pname, rc);
            return 1;
        }

        size_t sig_len = 0;
        rc = QUDO_SLHDSA_sign_ex(sig, sig_buf, &sig_len, test_msg,
                                 sizeof(test_msg), NULL, 0, NULL, sk);
        if (rc != QUDO_SLHDSA_SUCCESS) {
            fprintf(stderr, "ERROR: sign_ex(%s) = %d\n", pname, rc);
            return 1;
        }

        uint8_t sk_sha[32], pk_sha[32], sig_sha[32];
        sha2_256(sk_sha, sk, sk_len);
        sha2_256(pk_sha, pk, pk_len);
        sha2_256(sig_sha, sig_buf, sig_len);

        char buf[256];

        printf("/* --- slh_dsa_%s (pk=%zu, sk=%zu, sig=%zu, n=%zu) --- */\n\n",
               cname, pk_len, sk_len, sig_len, n);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_sk_seed", cname);
        print_array(buf, sk_seed, n);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_sk_prf", cname);
        print_array(buf, sk_prf, n);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_pk_seed", cname);
        print_array(buf, pk_seed, n);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_sk", cname);
        print_array(buf, sk, sk_len);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_sk_sha256", cname);
        print_array(buf, sk_sha, 32);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_pk_sha256", cname);
        print_array(buf, pk_sha, 32);

        snprintf(buf, sizeof(buf), "slh_dsa_%s_sig_sha256", cname);
        print_array(buf, sig_sha, 32);

        QUDO_SLHDSA_free(sig);
        free(pk);
        free(sk);
        free(sig_buf);
    }

    printf("\n/* Table entries for qudo_kat_slhdsa_tests[] */\n");
    for (i = 0; i < 12; i++) {
        printf("    {\n");
        printf("        \"%s KAT\", \"%s\",\n", param_names[i], param_names[i]);
        printf("        %zu,\n", n_vals[i]);
        printf("        slh_dsa_%s_sk_seed,\n", c_names[i]);
        printf("        slh_dsa_%s_sk_prf,\n", c_names[i]);
        printf("        slh_dsa_%s_pk_seed,\n", c_names[i]);
        printf("        slh_dsa_%s_sk, %zu,\n", c_names[i], n_vals[i] * 4);
        printf("        mldsa_test_msg, sizeof(mldsa_test_msg),\n");
        printf("        slh_dsa_%s_sk_sha256,\n", c_names[i]);
        printf("        slh_dsa_%s_pk_sha256,\n", c_names[i]);
        printf("        slh_dsa_%s_sig_sha256\n", c_names[i]);
        printf("    },\n");
    }

    return 0;
}
