/* SPDX-License-Identifier: Apache-2.0 AND MIT */

#ifndef MLKEM_NATIVE_ALL_H
#define MLKEM_NATIVE_ALL_H

#define MLK_CONFIG_PARAMETER_SET 512
#define MLK_CONFIG_MULTILEVEL_WITH_SHARED
#define MLK_CONFIG_NAMESPACE_PREFIX mlkem
#define MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#define MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#include "../mlkem-native/mlkem/mlkem_native.h"
#undef MLK_CONFIG_PARAMETER_SET
#undef MLK_CONFIG_MULTILEVEL_WITH_SHARED
#undef MLK_CONFIG_NAMESPACE_PREFIX
#undef MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#undef MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#undef MLK_TOTAL_ALLOC_512_KEYPAIR
#undef MLK_TOTAL_ALLOC_768_KEYPAIR
#undef MLK_TOTAL_ALLOC_1024_KEYPAIR
#undef MLK_H

#define MLK_CONFIG_PARAMETER_SET 768
#define MLK_CONFIG_MULTILEVEL_NO_SHARED
#define MLK_CONFIG_NAMESPACE_PREFIX mlkem
#define MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#define MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#include "../mlkem-native/mlkem/mlkem_native.h"
#undef MLK_CONFIG_PARAMETER_SET
#undef MLK_CONFIG_MULTILEVEL_NO_SHARED
#undef MLK_CONFIG_NAMESPACE_PREFIX
#undef MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#undef MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#undef MLK_TOTAL_ALLOC_512_KEYPAIR
#undef MLK_TOTAL_ALLOC_768_KEYPAIR
#undef MLK_TOTAL_ALLOC_1024_KEYPAIR
#undef MLK_H

#define MLK_CONFIG_PARAMETER_SET 1024
#define MLK_CONFIG_MULTILEVEL_NO_SHARED
#define MLK_CONFIG_NAMESPACE_PREFIX mlkem
#define MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#define MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#include "../mlkem-native/mlkem/mlkem_native.h"
#undef MLK_CONFIG_PARAMETER_SET
#undef MLK_CONFIG_MULTILEVEL_NO_SHARED
#undef MLK_CONFIG_NAMESPACE_PREFIX
#undef MLK_CONFIG_USE_NATIVE_BACKEND_ARITH
#undef MLK_CONFIG_USE_NATIVE_BACKEND_FIPS202
#undef MLK_TOTAL_ALLOC_512_KEYPAIR
#undef MLK_TOTAL_ALLOC_768_KEYPAIR
#undef MLK_TOTAL_ALLOC_1024_KEYPAIR
#undef MLK_H

#endif
